#!/usr/bin/env sh

#       ___                       ___                         ___     
#      /\  \                     /\__\                       /\__\    
#     |::\  \       ___         /:/ _/_                     /:/ _/_   
#     |:|:\  \     /\__\       /:/ /\__\                   /:/ /\__\  
#   __|:|\:\  \   /:/__/      /:/ /:/ _/_   ___     ___   /:/ /:/ _/_ 
#  /::::|_\:\__\ /::\  \     /:/_/:/ /\__\ /\  \   /\__\ /:/_/:/ /\__\
#  \:\~~\  \/__/ \/\:\  \__  \:\/:/ /:/  / \:\  \ /:/  / \:\/:/ /:/  /
#   \:\  \        ~~\:\/\__\  \::/_/:/  /   \:\  /:/  /   \::/_/:/  / 
#    \:\  \          \::/  /   \:\/:/  /     \:\/:/  /     \:\/:/  /  
#     \:\__\         /:/  /     \::/  /       \::/  /       \::/  /   
#      \/__/         \/__/       \/__/         \/__/         \/__/    


# ▰▰▰ options ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰

export WAL_TAGS="+coast"

export DESKTOP_NAMES="1 2 3 4 5 6 7"

export COMPTON_BLUR=true


# ▰▰▰ default apps ▰▰▰▰▰▰▰▰▰▰▰▰

export EDITOR="nvim"
export VISUAL="code"
export TERMINAL="termite"
export BROWSER="brave"
export READER="zathura"
export FILE="lf"
export STATUSBAR="polybar"
export WM="bspwm"

