#!/usr/bin/env sh

#                     ___           ___         ___           ___           ___           ___     
#      _____         /\__\         /\  \       /\  \         /\  \         /\  \         /\__\    
#     /::\  \       /:/ _/_       /::\  \     _\:\  \       |::\  \       /::\  \       /:/  /    
#    /:/\:\  \     /:/ /\  \     /:/\:\__\   /\ \:\  \      |:|:\  \     /:/\:\__\     /:/  /     
#   /:/ /::\__\   /:/ /::\  \   /:/ /:/  /  _\:\ \:\  \   __|:|\:\  \   /:/ /:/  /    /:/  /  ___ 
#  /:/_/:/\:|__| /:/_/:/\:\__\ /:/_/:/  /  /\ \:\ \:\__\ /::::|_\:\__\ /:/_/:/__/___ /:/__/  /\__\
#  \:\/:/ /:/  / \:\/:/ /:/  / \:\/:/  /   \:\ \:\/:/  / \:\~~\  \/__/ \:\/:::::/  / \:\  \ /:/  /
#   \::/_/:/  /   \::/ /:/  /   \::/__/     \:\ \::/  /   \:\  \        \::/~~/~~~~   \:\  /:/  / 
#    \:\/:/  /     \/_/:/  /     \:\  \      \:\/:/  /     \:\  \        \:\~~\        \:\/:/  /  
#     \::/  /        /:/  /       \:\__\      \::/  /       \:\__\        \:\__\        \::/  /   
#      \/__/         \/__/         \/__/       \/__/         \/__/         \/__/         \/__/    


# ▰▰▰ load resources ▰▰▰▰▰▰▰▰▰▰▰▰

# load miele settings
. "$HOME/.config/miele/mielerc"


# ▰▰▰ autostart ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰

# hotkeys daemon
killall -q sxhkd
sxhkd &

# set wallpaper
~/scripts/wallpaper-manager/wal-set.sh $WAL_TAGS

# start ther status bar
pgrep polybar || ~/.config/polybar/launch.sh

# adjust mouse acceleration
xinput set-prop 14 300 -0.75


# ▰▰▰ settings ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰

# set desktop names
bspc monitor DP-1   -d $(echo "$DESKTOP_NAMES" | cut -f1-4 -d " ")
bspc monitor HDMI-0 -d $(echo "$DESKTOP_NAMES" | cut -f5-9 -d " ")
bspc monitor LVDS-1 -d $(echo "$DESKTOP_NAMES" | cut -f1-9 -d " ")

# have border only on focused windows
bspc config border_width 1
pkill -f border-on-focused.sh
"$MIELE_SCRIPTS"/bspwm/border-on-focused.sh 1 &

bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^5'
