#! /bin/sh

#                     ___           ___         ___           ___           ___           ___     
#      _____         /\__\         /\  \       /\  \         /\  \         /\  \         /\__\    
#     /::\  \       /:/ _/_       /::\  \     _\:\  \       |::\  \       /::\  \       /:/  /    
#    /:/\:\  \     /:/ /\  \     /:/\:\__\   /\ \:\  \      |:|:\  \     /:/\:\__\     /:/  /     
#   /:/ /::\__\   /:/ /::\  \   /:/ /:/  /  _\:\ \:\  \   __|:|\:\  \   /:/ /:/  /    /:/  /  ___ 
#  /:/_/:/\:|__| /:/_/:/\:\__\ /:/_/:/  /  /\ \:\ \:\__\ /::::|_\:\__\ /:/_/:/__/___ /:/__/  /\__\
#  \:\/:/ /:/  / \:\/:/ /:/  / \:\/:/  /   \:\ \:\/:/  / \:\~~\  \/__/ \:\/:::::/  / \:\  \ /:/  /
#   \::/_/:/  /   \::/ /:/  /   \::/__/     \:\ \::/  /   \:\  \        \::/~~/~~~~   \:\  /:/  / 
#    \:\/:/  /     \/_/:/  /     \:\  \      \:\/:/  /     \:\  \        \:\~~\        \:\/:/  /  
#     \::/  /        /:/  /       \:\__\      \::/  /       \:\__\        \:\__\        \::/  /   
#      \/__/         \/__/         \/__/       \/__/         \/__/         \/__/         \/__/    


# ▰▰▰ autostart ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰

killall -q sxhkd
sxhkd &

#feh --randomize --bg-fill ~/Pictures/wallpapers/japanese-art/* &
wal -i $(cat ~/.config/wal/wallpapers | shuf -n 1) -o ~/.config/wal/done.sh &

pgrep polybar || ~/.config/polybar/launch.sh

killall -q dunst
dunst &

killall -q compton
compton -b &

pgrep mopidy || (mopidy --config ~/.config/mopidy &)

# adjust mouse acceleration
xinput set-prop 14 300 -0.75


# ▰▰▰ settings ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰

# greek numbers
#bspc monitor DP-1   -d α β γ δ
#bspc monitor HDMI-0 -d ε ϛ ζ

# japanese numbers
bspc monitor DP-1   -d 一 二 三 四
bspc monitor HDMI-0 -d 五 六 七

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^5'
